**Antes que nada correr esta celda para poder usar julia**

In [ ]:
# Installation cell
%%capture
%%shell
if ! command -v julia 3>&1 > /dev/null
then
    wget -q 'https://julialang-s3.julialang.org/bin/linux/x64/1.6/julia-1.6.1-linux-x86_64.tar.gz' \
        -O /tmp/julia.tar.gz
    tar -x -f /tmp/julia.tar.gz -C /usr/local --strip-components 1
    rm /tmp/julia.tar.gz
fi
julia -e 'using Pkg; pkg"add IJulia; precompile;"'
echo 'Done'

Despues de ejecutar la celda de arriba, Vamos a la barra de opciones de google colab y tocamos en **Editar** y despues en **Configuración del cuaderno** que está abajo de todo casi. Seleccionamos *Julia 1.6* en Tipo de Entorno de Ejecución. Y si queremos cambiamos el acelerador por hardware (default en GPU, les recomiendo que lo saquen). 

<br/>Editar y configuración

> ![Colab Img](https://i.imgur.com/7XLVAMN.png)

<br/>Esta es la configuración que deberian tener:

> ![Colab Img](https://i.imgur.com/UasidBO.png)

<br/>No se olviden de guardar.
<br/>**Arrancamos nomas, recuerden que siempre que se reinicie el entorno o lo que sea ejecuten esto**.






In [ ]:
VERSION #Para ver la version de julia

v"1.6.1"

#Fuentes de donde se saca info para ir completando

##Fuentes:
### La de los fideos  
![Colab Img](https://i.imgur.com/YZNNQiS.jpg)
### La de los deseos 
![Colab Img](https://i.imgur.com/Muez4aC.jpeg)
### Miami me lo confirmó
![Colab Img](https://i.ytimg.com/vi/ysmSWmTkNi8/sddefault.jpg)

## Mentira chinchulin ahi van los links:
### https://introajulia.org/ -> Bastante completa la wea
### https://es.xcv.wiki/wiki/Multiple_dispatch -> Multiple_Dispatch pa los pi
### https://julialang.org/blog/2012/02/why-we-created-julia/ -> Por qué se creo Julia (ingles)
### https://docs.julialang.org/en/v1/ -> Documentación Julia (Ingles)
### https://julialang.org/benchmarks/ -> Comparaciones con Julia y otros lenguajes
### https://es.wikipedia.org/wiki/Julia_(lenguaje_de_programaci%C3%B3n) -> La vieja confiable
### https://en.wikipedia.org/wiki/List_of_algorithms -> Lista de algoritmos para afanar a lo loco
### https://github.com/jltabara/Julia-y-las-Matematicas/blob/master/Julia01.md -> Matemática básica

##Hola mundo

In [ ]:
println("Hello World")

Hello World


##0.0 Cosas basicas

**Palabras reservadas en Julia**

![Colab Img](https://i.imgur.com/l0KZQ4n.png)

**Operadores aritmeticos**

    Suma:
    4 + 4 = 8

    Resta:
    4 - 2 = 2

    Multiplicación:
    4 * 4 = 16

    División:
    8/2 = 4

    Potencia:
    4^4 = 16

    Con strings:

    primer_str = "auto"
    segundo_str = "móvil"

    primer_str * segundo_str = automóvil

    "Spam"^3 = SpamSpamSpam

    Recordar que el orden de las operaciones es el siguiente:
    * Parentesis
    * Potenciación
    * Multiplicación y División
    * Suma resta etc (de izq a der)

**Tipos de datos**

Los enteros pertenecen al tipo **Int64**, las cadenas pertenecen a **String** y los números de punto flotante pertenecen a **Float64**.

    4 = Int64

    42.0 = Float64

    "Hola mundo" = String

    "42" = String

**Expresiones booleanas**

    5 == 5 = true

    5 == 6 = false

    Operadores relacionales:

    * == 
    * !=
    * >=
    * <=

    Operadores Logicos: 

    * &&
    * ||
    * !

**Condicionales**

    *(1)
    if x > 0
      println("Es positivo como el covid")
    end

    *(2)
    if x > 2
      algo()
    else 
      algo2()  
    end

    *(3)
    if alternativa == "a"
      dibujar_a()
    elseif alternativa == "b"
      dibujar_b()
    elseif alternativa == "c"
      dibujar_c()
    end

    (4)

    if x > 2 && x < 20
      if x == 4
        hacer algo
      end
    end

**Especificar un tipo de dato**

Para especificar un tipo de dato esperado o usar un tipo de dato especifico se usan los "::" dos puntitos seguido al tipo de dato

**Definir un struct** 

    struct Nombre
      Wea::Tipo_de_dato
      wea_2::Tipo_de_dato_2
    end

**Warning**

**ESTA DECLARACION ES INMUTABLE** (nos tira error diciendo que no puede ser cambiado, que es inmutable)

**Fin del Warning**

**Para declarar un struct mutable se realiza de la siguiente manera**

    mutable struct Nombre
      Wea::Tipo_de_dato
      wea_2::Tipo_de_dato_2
    end


**Para acceder a un atributo/campo/loquesea**

    nombre_del_struct.campo

**Definir una función**
    # Si se crea algo dentro de esto es local!!!
    function imprimirletras(párametros)
      println("La concha de tu madre")
      println("AllBoys")
    end

**Recursividad**

    function cuentaregresiva(n)
        if n <= 0
            println("Despegue!")
        else
            print(n, " ")
            cuentaregresiva(n-1)
        end
    end

**Definir un método**

    begin
      nombre(parametros)
    end

**Errores**

Si se produce un **error durante una llamada a función**, Julia imprime el nombre de la función, el nombre de la función que la llamó, el nombre de la función que a su vez llamó a esta otra, y así sucesivamente hasta llegar a la función de más alto nivel Main.

En caso de ser una funcion recursiva que nunca para de llamarse a si misma hace una referencia a stackoverflowerror.


###0.1 Aplicando lo visto

#### 0.1.1 Ejemplo struct




In [1]:
struct Persona
  altura::Float64
  peso::Float64
end

In [2]:
Elfo = Persona(1.80,74)

Persona(1.8, 74.0)

In [3]:
Elfo isa Persona #El elfo realmente es una persona?

true

In [4]:
typeof(Elfo) #Confirmamos, es una persona

Persona

In [5]:
Elfo.altura

1.8

In [6]:
Elfo.peso

74.0

#### 0.1.2 Ejemplo de funcion

In [7]:
begin
  alturaPorPeso(alguien::Persona) = alguien.altura * alguien.peso
end

alturaPorPeso (generic function with 1 method)

In [8]:
alturaPorPeso_del_elfo = alturaPorPeso(Elfo)

133.20000000000002

In [9]:
if alturaPorPeso_del_elfo >= 3
  println("Tas pesadito pa")
end

Tas pesadito pa


#### 0.1.3 Otro ejemplo completo

In [10]:
#Definimos el struct
struct Rectangle
  width::Float64
  height::Float64
end

In [11]:
#Ejemplito cortito y al pie
#Funcion especifica y generica de Area

begin
  area(r::Rectangle) = r.width * r.height # r::Rectangle significa que recibe un objeto si o si que es de tipo rectangulo y que tiene esos 2 campos (Esta es la funcion especifica que recibe si o si un rectangulo)
  area(x) = x #(funcion generica que recibe cualquier pito) Funciona para cualquier tipo excepto para los rectangulos, que ya tiene una función especifica
end

area (generic function with 2 methods)

**Aclaración importante** Es necesario definir todos los métodos del mismo tipo dentro de ese begin y end (Por lo menos en esta versión de Julia, según lo que dicen en un video del año pasado, no lo testié)

In [12]:
#Ejemplito de como es la wea
r = Rectangle(1.0,2.5)

Rectangle(1.0, 2.5)

In [13]:
area(r)

2.5

In [14]:
pingo = 1
area(pingo)

1

In [15]:
area #Dice cuantas funciones tiene definidas

area (generic function with 2 methods)

In [16]:
function imprimircuadricula()
  println("+ - - - - + - - - - +")
  println("|         |         |")
  println("|         |         |")
  println("|         |         |")
  println("|         |         |")
  println("+ - - - - + - - - - +")
  println("|         |         |")
  println("|         |         |")
  println("|         |         |")
  println("|         |         |")
  println("+ - - - - + - - - - +")
end

imprimircuadricula (generic function with 1 method)

In [17]:
imprimircuadricula()

+ - - - - + - - - - +
|         |         |
|         |         |
|         |         |
|         |         |
+ - - - - + - - - - +
|         |         |
|         |         |
|         |         |
|         |         |
+ - - - - + - - - - +


##1.0 ¿Por qué Julia?

Julia fue lanzado originalmente en 2012 por Alan Edelman, Stefan Karpinski, Jeff Bezanson y Viral Shah. Es un lenguaje de programación gratuito y de código abierto.

La elección de un lenguaje de programación es siempre subjetiva. Para mí, las siguientes características de Julia son decisivas:

- Julia está desarrollado como un lenguaje de programación de alto rendimiento.

- Julia usa envío múltiple (**“multiple dispatch”** **(1.1)** en inglés), que le permite al programador elegir entre diferentes patrones de programación de acuerdo a la aplicación.

- Julia es un lenguaje de tipo dinámico que se puede usar fácilmente de forma interactiva.

- Julia tiene una sintaxis de alto nivel que es fácil de aprender.

- Julia es un lenguaje de programación con tipos opcionales, cuyos tipos de datos (definidos por el usuario) hacen que el código sea claro y robusto.

- Julia tiene una biblioteca estándar extendida, además, están disponibles numerosos paquetes de terceros.

Julia es un lenguaje de programación único, ya que resuelve el problema de los dos idiomas. No se necesita de ningún otro lenguaje de programación para escribir código de alto rendimiento. Esto no significa que ocurra automáticamente. Es responsabilidad del programador optimizar el código que genere cuellos de botella, aunque esto puede hacerse directamente en Julia.

## 1.1 Multiple dispatch


Es un concepto muy importante en Julia. Ahora ¿Que pingo significa esto ura?. Ya te explico chango, la cosa es así.

Nosotros cuando hablamos de un envio simple estamos hablando de un proceso en donde elegimos un método diferente o versión de una función dependiendo del tipo de entrada

Y el envio multiple (*Multiple dispatch*) significa que miramos todos los tipos de entrada para todos los argumentos de la función para elegir que método o versión vamos a llamar

In [ ]:
#Defino un numero complejo
cc = 3 +4im #Para definir un imaginario se pone im dsp del num

3 + 4im

In [ ]:
#Para poder ver que es lo que realmente hace Julia voy a usar un macro
@which cc + cc

+(z::Complex, w::Complex) in Base at complex.jl:275

Lo que me dice lo de arriba es que se usa un método que recibe dos numeros complejos y los suma.

Ahora vamos a ver que pasa si sumamos un numero real

In [ ]:
@which cc + 4 #como se pone tu hermana

+(z::Complex, x::Real) in Base at complex.jl:313

Vemos que ahora llama a otro método, entonces esto quiere decir que entre todas las funciones definidas para la suma llama especificamente a aquellas que reciba ciertos parametros esperados

In [ ]:
#Vuelvo a probar pero invirtiendo
@which 4 + cc

+(x::Real, z::Complex) in Base at complex.jl:312

In [ ]:
#Quiero ver cuantos métodos de "+" hay
+

+ (generic function with 190 methods)

**Nota importante**, cada vez que usamos este macro nos da un link a la implementación, tenganlo en cuenta

# Teoria de los pi
## TDL 2021 1C - Julia 

## Historia

Julia se inició en el año 2009, por sus creadores Jeff Bezanson, Stefan Karpinski, Viral B. Shah y Alan Edelman quienes se propusieron crear un lenguaje libre que fuera rápido y de alto nivel.

En el año 2012 el equipo explicó en su blog por qué fue creado Julia.

**Despues lo traduzco para los hinchas de boca**

"*In short, because we are greedy*"

"We want a language that's open source, with a liberal license. We want the speed of C with the dynamism of Ruby. We want a language that's homoiconic, with true macros like Lisp, but with obvious, familiar mathematical notation like Matlab. We want something as usable for general programming as Python, as easy for statistics as R, as natural for string processing as Perl, as powerful for linear algebra as Matlab, as good at gluing programs together as the shell. Something that is dirt simple to learn, yet keeps the most serious hackers happy. We want it interactive and we want it compiled.

(Did we mention it should be as fast as C?)

Despite all this power, we want the language to be simple and clean."

pa seguir dsp 

https://julialang.org/blog/2012/02/why-we-created-julia/

https://julialang.org/blog/2018/08/one-point-zero/


##Sintaxis

### Variables

### Estructura de datos

## Semantica

#Prueba de código (no dar bola)


In [ ]:
A = [2 1 ; 0 3]
B = [7 ; 9]
A\B

2-element Vector{Float64}:
 2.0
 3.0

In [ ]:
A = [1 2 3; 4 5 6; 7 8 9]
B = [1 0 0; 0 1 0; 0 0 1] 
C = A + B * A^10000


3×3 Matrix{Int64}:
 -6559232017705053999  -9002684889773068006   7000606311868469603
  1470319080572675602  -2516550971109228402  -6503421022791132406
 -8946873894859146413   3969582947554611202  -1560704283741182799

In [ ]:
using LinearAlgebra

v = zeros(Int64, 3)

3-element Vector{Int64}:
 0
 0
 0

In [ ]:
using LinearAlgebra

A_inicial = [3 2 2; 2 3 -2]

A = transpose(A_inicial) * A_inicial

m = 3
n = 3

# avas y aves
avas = eigvals(A)
aves = eigvecs(A)  # (estoy 80% seguro, porque no lo encuentro en bibliografia, que los da normalizados)
                   # act: los vectores efectivamente los da normalizados pero su norma puede llegar a ser 0.9999999999994, normalizandolos a mano de nuevo quedan 1.0

avas = sort(avas, rev=true)
D = diagm(avas)


# FORMO A SIGMA
for i in 1:m
  if avas[i] > 0
    avas[i] = sqrt(avas[i])
  else
    avas[i] = 0
  end
end

Z = diagm(avas)


# FORMO A V    
V = zeros(n,n)

for i in 1:n
  v = aves[:,i] ./ norm(aves[:,i])
  println(v)
  println(norm(aves[:,i]))
  println(norm(v))
  V[:,i] = v
end

V

[0.6666666666666669, -0.6666666666666665, -0.33333333333333337]
0.9999999999999997
1.0
[0.23570226039551576, -0.23570226039551564, 0.9428090415820635]
0.9999999999999999
1.0
[0.7071067811865476, 0.7071067811865476, 0.0]
0.9999999999999999
1.0


3×3 Matrix{Float64}:
  0.666667   0.235702  0.707107
 -0.666667  -0.235702  0.707107
 -0.333333   0.942809  0.0

###Problemas encontrados para DVS:
- U es dificil de sacar sin dejar algo muy sucio ya que cada u_i se divide por un valor singular que puede ser 0.
- https://github.com/JuliaLang/julia/issues/6965 debate por el mal funcionamiento de eigs
- Autovalores que deberian ser 0 son numeros negativos.